version: "3" # docker version
services: #specifying the nginx server details. You can name it anything. Instead of www in prev. project, we call it web here
  #For Server
  web:
    image: nginx:latest #this is for the registry where docker looks for the image to use to build the app
    ports:
      - "80:80" # for looking into our project on our local machine
      - "443:443" # for future SSL traffic
    volumes: # creating a mapping between the files and folders on our host system to preserve development data whenever we run "docker compose"
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # For PHP
  app: #application files will live in this image
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app

  # For mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped # to make sure our database is up and running all the time
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-php

  # For Redis
  volumes:
    mysqldata: # giving it this empty value will make docker figure out the best way and place to get publish data
